# ===============================
# = Debugging & Logging
# ===============================
debug: false
logging.level:
  net.sf.ehcache: debug
  org.hibernate.type: trace
  com.shipbroker.cargoprovider: debug

# ===============================
# = Server Settings
# ===============================
server:
  port: 8081

# ===============================
# = Application
# ===============================
spring:
  application:
    name: cargoprovider
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
  data:
# Spring data hangs when not set
    jpa.repositories.bootstrap-mode: default

# ===============================
# = Hibernate datasource
# =============================== 
  datasource:
    url: jdbc:postgresql://localhost:5432/shipbroker
    driver-class-name: org.postgresql.Driver
    initialization-mode: ALWAYS
    
# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
#      ddl-auto: validate
    database-platform: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        generate_statistics: true

  
# ===============================
# = cache - config
# ===============================   
        cache:
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          use_query_cache: 'true'
#          ehcache.missing_cache_strategy: create
      javax:
        persistance.sharedCache.mode: ENABLE_SELECTIVE
      
#      net.sf.ehcache.configurationResourceName: classpath:/cache/ehcache.xml
#      net.sf.ehcache.configurationResourceName: /src/main/resources/cache/ehcache.xml

# ===============================
# = liquibase - config
# ===============================
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
    
# ===============================
# = liquibase - config
# ===============================

eureka:
  instance:
    prefer-ip-address: true
