

spring:
  application:
    name: shipbroker-gateway
  zipkin:
    base-url: http://localhost:9411
  security:
    user:
      password: password
      name: user

server:
  port: 9090

eureka:
  client:
    register-with-eureka: false
    
logging:
  level:
    org.springframework.cloud.gateway: debug 
    
