# ===============================
# = Debugging & Logging
# ===============================
debug: false
server:
  port: 8085

# ===============================
# = Application
# ===============================
spring:
  application:
    name: failover-cargoprovider

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;
    driverClassName: org.h2.Driver
    username: sa    
    password: 
  
  h2.console.enabled: true

#    
# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'